const mongoose=require("mongoose")

const coursesSchema=new mongoose.Schema({
         courseName:{
            type:String,
            required:true,
            trim:true
         },
         description:{
            type:String,
            required:true,
            trim:true
         },
         totalCourseDuration:{
            type:Number
         },
         progress:{
            type:Number
         },
         instructor:{
            type:mongoose.Schema.Types.ObjectId,
            ref:"User",
            required:true
         },
         whatYouWillLearn:{
            type:String,
            trim:true
         },
         courseContent:[
            {
                type:mongoose.Schema.Types.ObjectId,
                ref:"Section",
             }
         ],
         ratingAndReveiw:[
            {
                type:mongoose.Schema.Types.ObjectId,
                ref:"RatingAndReview",
             }
         ],
         category:{
            type:mongoose.Schema.Types.ObjectId,
                ref:"Category",
                required:true
         },
         tag:
         {
            type:String,
            required:true
         },
         instructions:
         {
            type:String,
            required:true
         },
         price:{
           type:String,
           required:true 
         },
         thumbnail:{
           type:String,
           required:true 
         },
         students:[
            {
            type:mongoose.Schema.Types.ObjectId,
            ref:"User",
            }
         ],
         public_id:{
            type:String,
            required:true
         },
         status:{
            type:String,
            default:"Draft",
            enum:["Draft","Published"]
         }
},{timestamps:true})

module.exports=mongoose.model("Course",coursesSchema)